# Generated by Django 5.1.3 on 2024-11-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admission_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
